spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gdgrain?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    password: root
    username: root
  redis:
    host: 192.168.233.129
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888
COUNT_TIME: COUNT_TIME